[project]
name = "nh-flood-2d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.17"
dependencies = [
    "fastdb4py>=0.1.11",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "rasterio>=1.4.4",
    "taichi>=1.7.4",
]
